### ISSUE TITLE
Hi Mate! So Can your WebAR-project run for image tracking to render AR effect on that image?THX

### ISSUE THREAD

**Issue by Simon1059770342** [naganath/webAR-BeYourHero#1]

**Comment by naganath** [comment]
The project uses tensorflow.js  for image processing. It tracks only human bodies and returns only  the body points.  If you want to track a static image as u move around the screen, i suggest you use the ar.js library.

**Comment by Simon1059770342** [comment]
THX ! AR.js can only be used in the marker way but it can direct detect
common image. So any another opensource you could recommend?

naganath <notifications@github.com> 于2019年1月26日周六 上午3:18写道：
